---
records:
  - zone: 'example.com'
    name: '@'
    ip: 10.16.0.1
  - zone: 'example.com'
    name: 'www'
    ip: 10.16.0.1
  - zone: 'example.com'
    name: 'mail'
    ip: 10.16.0.2
  - zone: 'sample.net'
    name: '@'
    ip: 10.17.0.1