- name: Gather facts
  ansible.builtin.setup:

- name: Installeer CIFS utils
  apt:
    name: cifs-utils
    state: present
    update_cache: yes

- name: Maak mount point aan
  file:
    path: /mnt/appdata
    state: directory
    owner: root
    group: root
    mode: '0755'

- name: Zet credentials bestand neer
  template:
    src: credentials.j2
    dest: /etc/smbcredentials
    owner: root
    group: root
    mode: '0600'

- name: Voeg fstab entry toe voor persistente mount met brede toegang
  mount:
    path: /mnt/appdata
    src: "//{{ nas_host }}/{{ nas_share }}"
    fstype: cifs
    opts: "credentials=/etc/smbcredentials,iocharset=utf8,vers=3.0,file_mode=0777,dir_mode=0777,nounix,uid=0,gid=0"
    state: mounted

- name: Check if folder exists
  stat:
    path: /mnt/appdata/{{ ansible_hostname }}
  register: folder_stat

- name: Create folder if it does not exist
  file:
    path: /mnt/appdata/{{ ansible_hostname }}
    state: directory
    owner: root
    group: root
    mode: '0755'
  when: not folder_stat.stat.exists
