---
- hosts: docker
  become: yes
  gather_facts: true
  vars_files:
    - ../../vars/sudo.yml
  vars:
    ansible_become_pass: "{{ docker_sudo_pass }}"
  tags:
    - docker-mealie-install
    - docker-mealie
    - docker
    - mealie-install
    - mealie
  tasks:
  - name: Check if docker is installed
    ansible.builtin.command: docker --version
    register: docker_valid
    ignore_errors: yes

  - name: Install docker
    ansible.builtin.import_role:
      name: "../../roles/docker"
    when: docker_valid.failed
    tags:
      - ubuntu-vm-docker-install
      - ubuntu-docker-install

  - name: Install mealie
    ansible.builtin.import_role:
      name: "../../roles/mealie"
    tags:
      - mealie-install
      - docker-mealie-install