---
- hosts: docker
  become: yes
  gather_facts: true
  vars_files:
    - ../../vars/sudo.yml
    - ../../roles/technitium/vars/main.yml
  vars:
    ansible_become_pass: "{{ docker_sudo_pass }}"
  tags:
    - docker-portainer-install
    - docker-portainer
    - docker
    - portainer-install
    - portainer
  tasks:
  - name: Check if docker is installed
    ansible.builtin.command: docker --version
    register: docker_valid
    ignore_errors: yes

  - name: Install docker
    ansible.builtin.import_role:
      name: "../../roles/docker"
    when: docker_valid.failed
    tags:
      - ubuntu-vm-docker-install
      - ubuntu-docker-install

  - name: Install portainer
    ansible.builtin.import_role:
      name: "../../roles/portainer"
    tags:
      - portainer-install
      - docker-portainer-install