---
- hosts: docker
  become: yes
  gather_facts: true
  vars_files:
    - ../../vars/sudo.yml
    - ../../roles/nginx_proxy_manager/vars/main.yml
  vars:
    ansible_become_pass: "{{ docker_sudo_pass }}"
  tags:
    - ubuntu-nginx_proxy_manager-install
    - ubuntu-nginx_proxy_manager
    - ubuntu
    - nginx_proxy_manager-install
    - nginx_proxy_manager
  tasks:

  - name: Check if docker is installed
    ansible.builtin.command: docker --version
    register: docker_valid
    ignore_errors: yes

  - name: Install docker
    ansible.builtin.import_role:
      name: "../../roles/docker"
    when: docker_valid.failed
    tags:
      - ubuntu-vm-docker-install
      - ubuntu-docker-install
      
  - name: Install nginx proxy manager
    ansible.builtin.import_role:
      name: "../../roles/nginx_proxy_manager"
    tags:
      - ubuntu-vm-nginx_proxy_manager-install
      - ubuntu-nginx_proxy_manager-install
      - docker-nginx_proxy_manager-install
      - nginx_proxy_manager-install
