---
- hosts: dns
  become: yes
  gather_facts: true
  vars_files:
    - ../../vars/sudo.yml
    - ../../roles/technitium/vars/main.yml
  vars:
    ansible_become_pass: "{{ dns_sudo_pass }}"
  tags:
    - ubuntu-dns-install
    - ubuntu-dns
    - ubuntu
    - dns-install
    - dns
  tasks:
  - name: Check if docker is installed
    ansible.builtin.command: docker --version
    register: docker_valid
    ignore_errors: yes

  - name: Install docker
    ansible.builtin.import_role:
      name: "../../roles/docker"
    when: docker_valid.failed
    tags:
      - ubuntu-vm-docker-install
      - ubuntu-docker-install
      
  - name: Install technitium
    ansible.builtin.import_role:
      name: "../../roles/technitium"
    tags:
      - ubuntu-vm-technitium-install
      - ubuntu-technitium-install
      - docker-technitium-install
      - technitium-install
