---
- hosts: dns
  become: yes
  gather_facts: true
  vars_files:
    - ../../vars/sudo.yml
    - ../../roles/technitium/vars/main.yml
  vars:
    ansible_become_pass: "{{ dns_sudo_pass }}"
  tags:
    - ubuntu-dns-sync
    - ubuntu-dns
    - ubuntu
    - dns-sync
    - dns
  tasks:
  - name: Sync dns to technitium
    ansible.builtin.import_role:
      name: "../../roles/technitium"
      tasks_from: sync
    tags:
      - ubuntu-vm-technitium-sync
      - ubuntu-technitium-sync
      - docker-technitium-sync
      - technitium-sync
